// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Lead is the predicate function for lead builders.
type Lead func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
